# Generated by Django 2.0 on 2018-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0002_auto_20180109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='iRacing_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='personal_site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitch_channel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='youtube_channel',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
