# Generated by Django 2.0 on 2018-01-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0004_auto_20180109_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
