# Generated by Django 2.0 on 2018-01-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0010_auto_20180111_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
