# Generated by Django 2.0 on 2018-01-11 21:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0011_auto_20180111_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_test',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
