# Generated by Django 2.0 on 2018-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0012_article_content_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_test',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
