# Generated by Django 2.0 on 2018-01-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0013_auto_20180111_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, to='nomadmain.TeamMember'),
        ),
    ]
