# Generated by Django 2.0 on 2018-01-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadmain', '0016_auto_20180111_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
